# Generated by Django 4.1 on 2022-08-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_qr_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
