# Generated by Django 4.1 on 2022-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_qr_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='https://www.gravatar.com/avatar/20CE8A94D216B1260F92B93BAA9F8FC1?d=identicon', upload_to=''),
        ),
    ]
