# Generated by Django 4.1 on 2022-08-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_plan_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='email',
            new_name='user',
        ),
        migrations.AddField(
            model_name='plan',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
