# Generated by Django 4.1 on 2022-08-17 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0003_rename_email_plan_user_plan_count_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='joiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join', to=settings.AUTH_USER_MODEL),
        ),
    ]
