# Generated by Django 4.1 on 2022-08-17 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0004_plan_joiner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='joiner',
        ),
        migrations.AddField(
            model_name='plan',
            name='joiner',
            field=models.ManyToManyField(null=True, related_name='join', to=settings.AUTH_USER_MODEL),
        ),
    ]
