# Generated by Django 4.1 on 2022-08-18 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0005_remove_plan_joiner_plan_joiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='joiner',
            field=models.ManyToManyField(related_name='join', to=settings.AUTH_USER_MODEL),
        ),
    ]
