# Generated by Django 4.1 on 2022-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_alter_plan_joiner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='profile_image',
            field=models.URLField(null=True),
        ),
    ]
