# Generated by Django 4.1 on 2022-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_alter_plan_present_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='present_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='promise_time',
            field=models.IntegerField(null=True),
        ),
    ]
