# Generated by Django 4.1 on 2022-08-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='point',
            field=models.IntegerField(null=True),
        ),
    ]
